name: Gradle Kotlin CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services: 
      postgres:
        image: postgres 
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: pgpwdtest
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v3

    - name: Install PostgreSQL client
      run: |
        apt-get update
        apt-get install --yes postgresql-client
 
    - name: Create DB
      run: psql -h localhost -U postgres -c 'CREATE DATABASE "modiciodb";'
      env:
        PGPASSWORD: pgpwdtest


    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    -  name: Gradle Build Action
       uses: gradle/gradle-build-action@v2.9.0
       with:
          gradle-version: 8.4
          arguments: "build --scan"
   
