name: Gradle Kotlin CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    services: 
      postgres:
        image: postgres 
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: pgpwdtest
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v3

    - name: Install PostgreSQL client
      run: |
        apt-get update
        apt-get install --yes postgresql-client unzip
 
    - name: Create DB
      run: psql -h postgres -U postgres -c 'CREATE DATABASE "modiciodb";'
      env:
        PGPASSWORD: pgpwdtest


    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.9.0

    - name: Gradle Bild and Test
      run: ./gradlew clean test

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v4.0.0-beta.3
      with:
        fail_ci_if_error: true
        files: reports/jacoco/

    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          **/build/reports/
          **/build/test-results/
    
    - name: Gradle Build Doc HTML
      run: ./gradlew dokkaHtml
    
    - name: Push DOC
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.BOT_PUSH }}
      with:
        source_folder: 'build/dokka/html'
        destination_repo: 'modicio/modicio-docs'
        destination_folder: 'docs'
        destination_branch: 'main'
        user_email: ${{ secrets.BOT_MAIL }}
        user_name: 'modicio-bot'
        commit_msg: '[GHA] Publish Kotlin Doc'

   
