name: Gradle Kotlin CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgpwdtest
            # Set health checks to wait until postgres has started
          options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        ports:
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v3
 
    - name: Create data test database
      run: |
        PGPASSWORD=pgwdtest createdb -h localhost -p 5432 -U postgres modiciodb


    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
